"""
Django settings for music_app project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

#Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#Load .env.dev file
load_dotenv(BASE_DIR / ".env.dev")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pj9eri^3j3960y@=$qd7@9_ryl5!wh$_v*m$mheq(taj(n@^7l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#Specify login URL
LOGIN_URL = 'user_login'
LOGIN_REDIRECT_URL = 'the_feed/'

#Specify logout URL
LOGOUT_REDIRECT_URL = 'logout/'


# Application definition
# Required onyl for Django apps
INSTALLED_APPS = [
    # whitenoise_runserver_nostatic needs to remain the top entry in order to also use static file serving in debug.
    'whitenoise.runserver_nostatic',
    'crispy_forms',
    'admin_tools_stats',    # this must be BEFORE 'admin_tools' and 'django.contrib.admin'
    'django_nvd3',
    'nested_admin',
    'phonenumber_field',
    'django_db_logger',     # django database logging
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #My music_apps
    'music_app_auth',
    'music_app_archive',
    'music_app_social',
]

#Tell Django to use the CustomUser model instead of auth.User
AUTH_USER_MODEL = 'music_app_auth.CustomUser'

#Set AUTHENTICATION_BACKENDS variable to allow the user to login via the user's email
AUTHENTICATION_BACKENDS = ['music_app_auth.common.backends.EmailBackend']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.contrib.admindocs.middleware.XViewMiddleware",
]

ROOT_URLCONF = 'music_app_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'music_app_main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

#Specify the password validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'music_app_auth.common.validators.ContainsNumberValidator', # Path to your custom validator
        'OPTIONS': {
            'min_number': 1 # Require at least 1 numeric character
        }
    },
    {
        'NAME': 'music_app_auth.common.validators.SpecialCharacterValidator', # Path to your custom validator
        'OPTIONS': {
            'min_symbols': 1, # Require at least 1 special character
            'symbols': "!@#$%^&*()_+{}[]:;\"'<>,.?/\\|-" # Define the allowed special characters
        }
    }
]


# Mail functionality
#TODO update these settings below for functional testing.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_FROM = 'test_music_app@home.com'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Reference to platform API key's
YOUTUBE_API_KEY = os.environ.get("YOUTUBE_API_KEY")