name: 'music_app'
version: '1.0.0'
config-version: 2

profile: 'music_app'

#Paths
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


target-path: "target"

#Models
models:
  music_app:
      staging:
          +materialized: view #This will store every staging model as a view in Snowflake
          +schema: STAGING
      marts:
          +materialized: table #Physically store this in Snowflake
          +schema: MARTS
