# Generated by Django 4.2.20 on 2025-08-09 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
