# Generated by Django 4.2.20 on 2025-08-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_alter_customuser_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('log_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'ordering': ['user', '-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='AppLoggingIdx')],
            },
        ),
    ]
