# Generated by Django 4.2.20 on 2025-08-16 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_alter_applogging_timestamp_onetimetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimetoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
