# Generated by Django 4.2.20 on 2025-08-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_alter_onetimetoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimetoken',
            name='purpose',
            field=models.CharField(choices=[('AUTH', 'User authentication'), ('RESET_PASSWORD', 'Reset user password'), ('COLLAB_PLAYLIST', 'Playlist collaboration')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
