# Generated by Django 4.2.20 on 2025-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_onetimetoken_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimetoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
