# Generated by Django 4.2.20 on 2025-10-26 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('playlist_type', models.CharField(choices=[('tracks', 'Tracks'), ('liked', 'Liked'), ('mixes', 'Mixes'), ('samples', 'Samples'), ('labels', 'Labels')], default='tracks', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_private', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Playlist Owner')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['owner', '-date_created'], name='playlist_owner_date_idx'), models.Index(fields=['is_private', 'is_deleted', '-date_created'], name='playlist_public_feed_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('owner', 'playlist_name'), name='unique_owner_playlist_name'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_owner_slug'),
        ),
    ]
