# Generated by Django 4.2.20 on 2025-10-27 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app_archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_type',
            field=models.CharField(choices=[('tracks', 'Tracks'), ('liked', 'Liked'), ('mixes', 'Mixes'), ('samples', 'Samples')], default='tracks', max_length=50),
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_type', models.CharField(choices=[('track', 'Track'), ('mix', 'Mix'), ('sample', 'Sample')], default='track', max_length=20)),
                ('track_name', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('album_name', models.CharField(blank=True, max_length=250)),
                ('mix_page', models.CharField(blank=True, max_length=250)),
                ('record_label', models.CharField(blank=True, max_length=250)),
                ('genre', models.CharField(blank=True, max_length=250)),
                ('purchase_link', models.URLField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['track_name', 'artist'], name='track_name_artist_idx'), models.Index(fields=['-date_added'], name='track_date_added_idx')],
            },
        ),
    ]
