# Generated by Django 4.2.20 on 2025-10-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app_archive', '0002_alter_playlist_playlist_type_tracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_platform', models.CharField(choices=[('youtube', 'YouTube'), ('youtube_music', 'YouTube Music'), ('spotify', 'Spotify'), ('soundcloud', 'SoundCloud'), ('nina', 'Nina'), ('bandcamp', 'Bandcamp')], max_length=20)),
                ('streaming_link', models.URLField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaming_links', to='music_app_archive.tracks', verbose_name='Streamed on')),
            ],
            options={
                'indexes': [models.Index(fields=['track', 'streaming_platform'], name='track_streaming_idx'), models.Index(fields=['streaming_platform'], name='streaming_platform_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='streaminglinks',
            constraint=models.UniqueConstraint(fields=('track', 'streaming_platform'), name='unique_track_streaming_platform'),
        ),
    ]
