# Generated by Django 4.2.20 on 2025-10-28 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app_archive', '0003_streaminglinks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_platform', models.CharField(choices=[('youtube', 'YouTube'), ('youtube_music', 'YouTube Music'), ('spotify', 'Spotify'), ('soundcloud', 'SoundCloud'), ('nina', 'Nina'), ('bandcamp', 'Bandcamp')], max_length=20)),
                ('streaming_link', models.URLField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streaming_links_added', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'Streaming Link',
                'verbose_name_plural': 'Streaming Links',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_type', models.CharField(choices=[('track', 'Track'), ('mix', 'Mix'), ('sample', 'Sample')], default='track', max_length=20)),
                ('track_name', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('album_name', models.CharField(blank=True, max_length=250)),
                ('mix_page', models.CharField(blank=True, max_length=250)),
                ('record_label', models.CharField(blank=True, max_length=250)),
                ('genre', models.CharField(blank=True, max_length=250)),
                ('purchase_link', models.URLField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks_created', to=settings.AUTH_USER_MODEL, verbose_name='First Added By')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='StreamingLinks',
        ),
        migrations.DeleteModel(
            name='Tracks',
        ),
        migrations.AddField(
            model_name='streaminglink',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streaming_links', to='music_app_archive.track', verbose_name='Streamed on'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['track_name', 'artist'], name='track_name_artist_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['-date_added'], name='track_date_added_idx'),
        ),
        migrations.AddConstraint(
            model_name='streaminglink',
            constraint=models.UniqueConstraint(fields=('track', 'streaming_platform'), name='unique_track_streaming_platform'),
        ),
    ]
