# Generated by Django 4.2.20 on 2025-10-28 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app_archive', '0004_streaminglink_track_remove_tracks_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Position of track in playlist')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_tracks_added', to=settings.AUTH_USER_MODEL, verbose_name='Playlist Tracks Added')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_in_playlist', to='music_app_archive.playlist', verbose_name='Tracks in Playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='music_app_archive.track', verbose_name='Playlist entries')),
            ],
            options={
                'ordering': ['playlist', 'position'],
                'indexes': [models.Index(fields=['playlist', 'position'], name='playlist_position_idx'), models.Index(fields=['track'], name='track_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('playlist', 'track'), name='unique_playlist_track'),
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('playlist', 'position'), name='unique_playlist_position'),
        ),
    ]
