# Generated by Django 4.2.20 on 2025-11-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app_archive', '0005_playlisttrack_playlisttrack_unique_playlist_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='Position of track in playlist', null=True),
        ),
    ]
