# Generated by Django 4.2.20 on 2026-01-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app_archive', '0006_alter_playlisttrack_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaminglink',
            name='streaming_platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('youtube_music', 'YouTube Music'), ('bandcamp', 'Bandcamp')], max_length=20),
        ),
    ]
