# Generated by Django 4.2.20 on 2026-03-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app_archive', '0007_alter_streaminglink_streaming_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisttrack',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
