# Generated by Django 4.2.20 on 2026-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app_archive', '0008_playlisttrack_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaminglink',
            name='streaming_platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('youtube_music', 'YouTube Music'), ('bandcamp', 'Bandcamp'), ('soundcloud', 'SoundCloud')], max_length=20),
        ),
    ]
